// Generated by Hive CE
// Do not modify
// Check in to version control

import 'package:hive_ce/hive_ce.dart';
import 'package:cotv/src/models/habit.dart';
import 'package:cotv/src/models/journal_entry.dart';
import 'package:cotv/src/models/schedule_item.dart';
import 'package:cotv/src/models/task.dart';
import 'package:cotv/src/models/user_settings.dart';

extension HiveRegistrar on HiveInterface {
  void registerAdapters() {
    registerAdapter(HabitAdapter());
    registerAdapter(HabitFrequencyAdapter());
    registerAdapter(JournalEntryAdapter());
    registerAdapter(JournalMoodAdapter());
    registerAdapter(ScheduleItemAdapter());
    registerAdapter(TaskAdapter());
    registerAdapter(TaskPriorityAdapter());
    registerAdapter(UserSettingsAdapter());
  }
}

extension IsolatedHiveRegistrar on IsolatedHiveInterface {
  void registerAdapters() {
    registerAdapter(HabitAdapter());
    registerAdapter(HabitFrequencyAdapter());
    registerAdapter(JournalEntryAdapter());
    registerAdapter(JournalMoodAdapter());
    registerAdapter(ScheduleItemAdapter());
    registerAdapter(TaskAdapter());
    registerAdapter(TaskPriorityAdapter());
    registerAdapter(UserSettingsAdapter());
  }
}
